### ISSUE TITLE
when generating masks only certain options do not function properly

### ISSUE THREAD

**Issue by ride5k** [kex0/batch-face-swap#30]
generate masks only, does not seem to detect all faces (as if "first face only" is selected, but it is not)
also skipping empty masks does not seem to work (toggle does not change output)

**Comment by kex0** [comment]
> generate masks only, does not seem to detect all faces (as if "first face only" is selected, but it is not)

The way it works is it creates 1 mask per face, so you have to activate the 'Single mask per image' option if you want to combine them.
![chrome_VkqlQxz6E0](https://user-images.githubusercontent.com/46696708/223838808-618f4463-5889-4542-b155-b6637f3a0bb7.png)

> also skipping empty masks does not seem to work (toggle does not change output)

You're right. It is now fixed in the latest commit [e65f9d0](https://github.com/kex0/batch-face-swap/commit/e65f9d0db99f2b9b9c98779f50a4860a0dc91536)

Here's a short video that shows how it works.
https://www.youtube.com/watch?v=NthOWCmoBPA
