### ISSUE TITLE
Quality reduced with recent update (restore faces not working?)

### ISSUE THREAD

**Issue by robertdbruce** [kex0/batch-face-swap#63]
hello there!

I wonder if you could help with this.
Since your recent update / new UI I've been having odd issues.  (as far as I know the timing coincides anyway)

The eye quality / face quality looks very odd - it's almost as if the 'restore faces' option is no longer working

I've been testing with inpaint upload on img2img (as this worked before for a long time)

Attached example
![eyes](https://github.com/kex0/batch-face-swap/assets/134811671/c8409f68-28de-4dfd-b7a8-198a73589bd8)

is using DPM++ 2M Karras / 40 sampling steps and face restoration model is GFPGAN

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Automatic1111 Version: v1.3.0

- Checkpoint used (I've tried many) - but all based on SD 1.5
- Image Size = 512 x 512

Thanks in advance!

**Comment by kex0** [comment]
I can't replicate your results. Although I always preferred inpainted faces over built-in face restoration. That's why I made this extension. I never saw eyes this messed up.

If you want, please send me one of the original photos where this is happening, with exact prompt and settings.

**Comment by robertdbruce** [comment]
okay here's a better example (with base input images attached as a zip)
![output2](https://github.com/kex0/batch-face-swap/assets/134811671/b3d9aa95-23dd-4549-a515-e53161bd3525)
![manual_inaint](https://github.com/kex0/batch-face-swap/assets/134811671/273702c9-4256-4789-af81-05b63c099791)



[base input images.zip](https://github.com/kex0/batch-face-swap/files/11638773/base.input.images.zip)

![settings_and_output](https://github.com/kex0/batch-face-swap/assets/134811671/a97f5422-3d39-49bd-ba8a-829d15ce4242)
![other_settings](https://github.com/kex0/batch-face-swap/assets/134811671/9674af65-5d0e-4bdb-9658-e9313d904f39)

seems to work well with higher resolution base images but once they're any way reduced in quality the eyes start messing up.
But manual inpainting with a similar size mask works fine.

I've tried working from a new clean version of SD as well, no other extensions or embeddings, exact same output.

any ideas ?

**Comment by robertdbruce** [comment]
oh and the images always seem to appear slightly older as well, it's very odd 🤷

**Comment by kex0** [comment]
I did some testing and I still don't really see any meaningful difference between manual inpainting and automatic. From the example you sent it looks to me like the output from manual inpainting had much higher `Only masked padding, pixels` value than the automatic. Or perhaps used lower `CFG Scale` or different SD model.

In my testing I used your exact settings except in the prompt I used `Liv Tyler` instead of `sks` and for the manual inpainting I kept the deffault values for `Only masked padding, pixels` (32) and `Mask blur` 4, for all pictures. In the inpainting with extension I did activate the `Override "Mask blur" to automatic` and `Override "Only masked padding, pixels" to automatic` checkboxes.

Here are my results:
[DOWNLOAD](https://github.com/kex0/batch-face-swap/files/11644275/test.zip)
From left to right: Batch Face Swap, Batch Face Swap + Face Restoration, Manual, Manual + Face restoration
![bfs_bfs+restore_manual_manual+restore](https://github.com/kex0/batch-face-swap/assets/46696708/64570efe-9549-49ca-b4ee-8938a9463b0f)
![bfs_bfs+restore_manual_manual+restore2](https://github.com/kex0/batch-face-swap/assets/46696708/6c03a7d4-c5e8-4ecd-86b1-0abb5f939c6e)
![bfs_bfs+restore_manual_manual+restore3](https://github.com/kex0/batch-face-swap/assets/46696708/8516913d-2cd3-4f3c-a29c-588cdcf8567b)
![bfs_bfs+restore_manual_manual+restore4](https://github.com/kex0/batch-face-swap/assets/46696708/7ac76243-5ec0-4d10-a7ec-510e0797834c)
![bfs_bfs+restore_manual_manual+restore5](https://github.com/kex0/batch-face-swap/assets/46696708/7e515004-e09a-4bcf-af54-f4e9945159f0)
![bfs_bfs+restore_manual_manual+restore6](https://github.com/kex0/batch-face-swap/assets/46696708/df44ef22-bb1e-4441-bb9b-06c3c8828e3c)

**Comment by robertdbruce** [comment]
The quality! wow.  My one used to be *almost* this good. I miss it :-) -  VAE in use ?

I test using same model and same settings always.

Thanks for trying anyway. I'm not sure what the hell is going on LOL. Maybe my GPU is busted :-)

**Comment by kex0** [comment]
I used this model https://civitai.com/models/8030?modelVersionId=56498
and the same VAE as you've shown in your screenshot.
